import Link from "next/link"
import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/ssg">SSG</Link>
            <Link href="/ssr">SSR</Link>
            <Link href="/csr">CSR</Link>
            <Link href="/isr">ISR</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
